### ISSUE TITLE
Clean data (in and out)

### ISSUE THREAD

**Issue by HeinzNepe** [recalstudios/recal-social-api#13]
Make all special characters into percentage characters

**Comment by theS1LV3R** [comment]
https://stackoverflow.com/questions/575440/url-encoding-using-c-sharp#11236038

**Comment by HeinzNepe** [comment]
has been closed in the API

**Comment by HeinzNepe** [comment]
Nevermind :-)

**Comment by soni801** [comment]
This should be closed i think
